# Generated by Django 3.2 on 2021-11-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potion',
            name='name',
        ),
    ]
