# Generated by Django 3.2 on 2021-11-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='nap',
            field=models.TimeField(),
        ),
    ]
