# Generated by Django 3.2 on 2021-11-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloversoldier',
            name='letter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cloversoldier',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='diamondsoldier',
            name='letter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diamondsoldier',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='heartsoldier',
            name='letter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heartsoldier',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spadesoldier',
            name='letter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spadesoldier',
            name='strength',
            field=models.IntegerField(null=True),
        ),
    ]
